defmodule Pdf.DevServer.Examples.Component.PageHeaderDemo do
  @moduledoc false

  def render do
    dark = {0.1, 0.1, 0.1}
    gray = {0.5, 0.5, 0.5}
    blue = {0.23, 0.55, 0.83}

    Pdf.new(size: :a4, margin: %{top: 60, bottom: 50, left: 50, right: 50})
    |> Pdf.set_info(title: "PageHeader + Paginator Demo")

    # Header on every page
    |> Pdf.Component.PageHeader.apply(%{
      title: "Monthly Report — Q4 2026",
      subtitle: "Generated by ExPDF Components",
      right: :date,
      color: dark,
      line: true,
      line_color: blue,
      line_width: 1
    })

    # Footer with page numbers
    |> Pdf.Component.Paginator.apply(%{
      format: :center,
      font_size: 8,
      color: gray,
      prefix: "Page ",
      show_total: true,
      total_pages: 3,
      separator: " of "
    })

    # ── Page 1 ──
    |> Pdf.set_font("Helvetica", 14, bold: true)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 700}, "Page Header + Paginator Demo")
    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.set_fill_color(gray)
    |> Pdf.text_at({50, 682}, "This document demonstrates automatic headers and footers on every page.")
    |> Pdf.text_at({50, 668}, "The header shows the report title, subtitle, date, and a colored line.")
    |> Pdf.text_at({50, 654}, "The footer shows centered page numbers with total count.")

    |> Pdf.set_font("Helvetica", 12, bold: true)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 620}, "Features:")
    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({70, 602}, "- Centered title with optional subtitle")
    |> Pdf.text_at({70, 588}, "- Left/right layout for company name + date")
    |> Pdf.text_at({70, 574}, "- Auto date (:date) or page number (:page) on right side")
    |> Pdf.text_at({70, 560}, "- Horizontal separator line with custom color and width")
    |> Pdf.text_at({70, 546}, "- Option to skip header on first page")
    |> Pdf.text_at({70, 532}, "- Combine with Paginator for full header + footer")

    # ── Page 2 ──
    |> Pdf.add_page(:a4)
    |> Pdf.set_font("Helvetica", 14, bold: true)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 700}, "Section 1: Executive Summary")
    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 680}, "This page has the same header and footer applied automatically.")
    |> Pdf.text_at({50, 664}, "No manual rendering needed — the on_page hooks handle it.")

    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.set_fill_color(gray)
    |> Pdf.text_at({50, 630}, "Lorem ipsum dolor sit amet, consectetur adipiscing elit.")
    |> Pdf.text_at({50, 616}, "Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.")
    |> Pdf.text_at({50, 602}, "Ut enim ad minim veniam, quis nostrud exercitation ullamco.")

    # ── Page 3 ──
    |> Pdf.add_page(:a4)
    |> Pdf.set_font("Helvetica", 14, bold: true)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 700}, "Section 2: Financial Data")
    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.set_fill_color(dark)
    |> Pdf.text_at({50, 680}, "Third page — header and footer still consistent across all pages.")

    # Simple table to show it works with other content
    |> Pdf.set_font("Helvetica", 10)
    |> Pdf.table!(
      {50, 640}, {495, 200},
      [
        ["Category", "Q3 2026", "Q4 2026", "Change"],
        ["Revenue",  "$1.2M",   "$1.5M",   "+25%"],
        ["Expenses", "$800K",   "$850K",   "+6%"],
        ["Profit",   "$400K",   "$650K",   "+62%"]
      ],
      padding: 6,
      border: 0.5,
      rows: %{
        0 => [bold: true, background: {0.92, 0.92, 0.95}],
        -1 => [bold: true, background: {0.9, 0.95, 0.9}]
      }
    )

  end
end
