defmodule Pdf.Reader.UnifiedReadTest do
  @moduledoc """
  Tests for `Pdf.Reader.read/2` — single call returns the full
  `%Pdf.Reader.Result{}` with meta + per-page lines (text + images).
  """
  use ExUnit.Case, async: true

  alias Pdf.Reader.{Line, Result, Shape}

  @csf_path Path.join([__DIR__, "..", "..", "..", "priv", "pdf", "csf.pdf"])

  describe "Pdf.Reader.read/2 — full document" do
    test "returns a %Result{meta, pages} struct" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      assert {:ok, %Result{} = result, _doc} = Pdf.Reader.read(doc)

      assert is_map(result.meta)
      assert is_list(result.pages)
      assert length(result.pages) == 2
      assert Enum.all?(result.pages, &is_struct(&1, Result.Page))
    end

    test "default is equivalent to shape: :document" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, default, _} = Pdf.Reader.read(doc)
      {:ok, explicit, _} = Pdf.Reader.read(doc, shape: :document)
      assert default == explicit
    end
  end

  describe "result.meta — document-level metadata" do
    test "carries the normalised Info-dict fields" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{meta: meta}, _} = Pdf.Reader.read(doc)

      # Standard keys exposed as atoms (nil when absent).
      assert Map.has_key?(meta, :title)
      assert Map.has_key?(meta, :author)
      assert Map.has_key?(meta, :subject)
      assert Map.has_key?(meta, :keywords)
      assert Map.has_key?(meta, :creator)
      assert Map.has_key?(meta, :producer)
      assert Map.has_key?(meta, :creation_date)
      assert Map.has_key?(meta, :mod_date)

      # CSF was generated by Oracle XML Publisher.
      assert meta.producer == "Oracle XML Publisher 5.6.2"
    end

    test "carries derived fields (page_count, version, encrypted, recovery_log, raw)" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{meta: meta}, _} = Pdf.Reader.read(doc)

      assert meta.page_count == 2
      assert meta.version == "1.7"
      assert meta.encrypted == false
      assert meta.recovery_log == []
      assert is_map(meta.raw)
      assert Map.get(meta.raw, "Producer") == "Oracle XML Publisher 5.6.2"
    end
  end

  describe "result.pages — per-page slices" do
    test "each page has number, meta, and lines" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      Enum.each(pages, fn page ->
        assert page.number in 1..2
        assert is_map(page.meta)
        assert is_list(page.lines)
        assert Enum.all?(page.lines, &is_struct(&1, Line))
      end)
    end

    test "lines on each page are sorted top-to-bottom by Y" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      Enum.each(pages, fn page ->
        ys = Enum.map(page.lines, & &1.y)
        assert ys == Enum.sort(ys, :desc)
      end)
    end

    test "every line belongs to its containing page" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      Enum.each(pages, fn page ->
        Enum.each(page.lines, fn line ->
          assert line.page == page.number
        end)
      end)
    end
  end

  describe "tokens within result.pages.lines" do
    test "every token has :kind and :shape" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      pages
      |> Enum.flat_map(& &1.lines)
      |> Enum.flat_map(& &1.tokens)
      |> Enum.each(fn token ->
        assert Map.has_key?(token, :kind)
        assert Map.has_key?(token, :shape)
        assert token.kind in [:text, :link, :email, :image]
      end)
    end

    test "URL token has kind: :link" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      url =
        pages
        |> Enum.flat_map(& &1.lines)
        |> Enum.flat_map(& &1.tokens)
        |> Enum.find(&(&1.shape != nil and &1.shape.target == "http://sat.gob.mx"))

      assert url.kind == :link
    end

    test "image tokens carry data_uri but no raw :bytes by default" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc)

      images =
        pages
        |> Enum.flat_map(& &1.lines)
        |> Enum.flat_map(& &1.tokens)
        |> Enum.filter(&(&1.kind == :image))

      assert length(images) == 9

      Enum.each(images, fn t ->
        assert is_binary(t.shape.meta.data_uri)
        # By default the lightweight result drops the raw bytes —
        # callers that need them pass `image_bytes: true`.
        refute Map.has_key?(t.shape.meta, :bytes)
        # byte_size of the source binary is still reported for sizing.
        assert is_integer(t.shape.meta.byte_size)
      end)
    end

    test "image_bytes: true attaches :bytes alongside data_uri" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, %Result{pages: pages}, _} = Pdf.Reader.read(doc, image_bytes: true)

      images =
        pages
        |> Enum.flat_map(& &1.lines)
        |> Enum.flat_map(& &1.tokens)
        |> Enum.filter(&(&1.kind == :image))

      Enum.each(images, fn t ->
        assert is_binary(t.shape.meta.bytes)
        assert byte_size(t.shape.meta.bytes) == t.shape.meta.byte_size
        assert is_binary(t.shape.meta.data_uri)
      end)
    end
  end

  describe "convenience shapes" do
    test "shape: :text returns plain text pages" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, pages, _} = Pdf.Reader.read(doc, shape: :text)
      assert is_list(pages)
      assert length(pages) == 2
      assert Enum.all?(pages, &is_binary/1)
    end

    test "shape: :shapes returns the flat shape list" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      {:ok, shapes, _} = Pdf.Reader.read(doc, shape: :shapes)
      assert is_list(shapes)
      assert Enum.all?(shapes, &is_struct(&1, Shape))
    end
  end

  describe "errors" do
    test "unknown shape returns {:error, {:unknown_shape, _}}" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      assert {:error, {:unknown_shape, :tabla}} = Pdf.Reader.read(doc, shape: :tabla)
    end
  end

  describe "Pdf.Reader.read!/2" do
    test "returns the value directly on success" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      assert %Result{} = result = Pdf.Reader.read!(doc)
      assert length(result.pages) == 2
    end

    test "raises on unknown shape" do
      {:ok, doc} = Pdf.Reader.open(@csf_path)
      assert_raise Pdf.Reader.Error, fn -> Pdf.Reader.read!(doc, shape: :tabla) end
    end
  end
end
